# Generated by Django 2.1.7 on 2019-03-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_merchant'),
        ('Advisory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advisor',
            new_name='Advise',
        ),
    ]
