# Generated by Django 2.1.7 on 2019-03-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20190302_0740'),
        ('Authentication', '0004_merchant'),
        ('Advisory', '0002_auto_20190302_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Advise',
            new_name='Advice',
        ),
        migrations.AddField(
            model_name='advicecategory',
            name='advice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advisory.Advice'),
        ),
        migrations.AddField(
            model_name='advicecategory',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Crop'),
        ),
    ]
