# Generated by Django 2.1.7 on 2019-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_rent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.AlterModelOptions(
            name='cartdetail',
            options={'verbose_name': 'CartDetail', 'verbose_name_plural': 'CartDetails'},
        ),
        migrations.AlterModelOptions(
            name='rent',
            options={'verbose_name': 'Rent', 'verbose_name_plural': 'Rents'},
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
