# Generated by Django 2.1.7 on 2019-03-02 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('product_type', models.CharField(choices=[('SEED', 'SEED'), ('MANURE', 'MANURE'), ('TRACTOR', 'TRACTOR'), ('EQUIPMENT', 'EQUIPMENT'), ('OTHER', 'OTHER')], max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.FloatField()),
                ('quantity_type', models.CharField(choices=[('PCS', 'PCS'), ('KG', 'KG'), ('LTR', 'LTR'), ('OTHER', 'OTHER')], max_length=5)),
                ('image', models.FileField(upload_to='static/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.UserDetail')),
            ],
        ),
    ]
