# Generated by Django 2.1.7 on 2019-03-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_crop_farmercrop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='period',
            field=models.CharField(choices=[('LESS_THAN_ONE_YEAR', 'LESS_THAN_ONE_YEAR'), ('ONE_TO_FIVE_YEAR', 'ONE_TO_FIVE_YEAR'), ('GREATER_THAN_FIVE', 'GREATER_THAN_FIVE')], default='LESS_THAN_ONE_YEAR', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_type',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], default='BUY', max_length=12),
        ),
    ]
