# Generated by Django 2.1.7 on 2019-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_auto_20190302_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='name',
            field=models.CharField(default='Kisaan Mitra', max_length=32),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SEED', 'SEED'), ('MANURE', 'MANURE'), ('VEHICLE', 'VEHICLE'), ('EQUIPMENT', 'EQUIPMENT'), ('OTHER', 'OTHER')], max_length=120),
        ),
    ]
