# Generated by Django 2.1.7 on 2019-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_auto_20190302_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='static/uploads/products/'),
        ),
    ]
