# Generated by Django 2.1.7 on 2019-03-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(default='abcd@gmail.com', max_length=254),
        ),
    ]
